spring:

#  Database
  datasource:
    url: jdbc:postgresql://localhost:5432/ftg-car
    username: ftg-car
    password: password

# JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        #TODO : voir pour un  ddl_auto: 

# API
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED
      allowedOrigins: http://localhost:4200
server:
  port: 4444
  