spring:
  #  Database
  datasource:
    url: jdbc:postgresql://localhost:5432/ftg-car
    username: ftg-car
    password: password

  # JPA
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  flyway:
    baseline-on-migrate: true

  # API
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED
      allowedOrigins: http://localhost:4200
server:
  port: 4444
